"""empty message

Revision ID: df1b99bb595b
Revises: 774a1913edb2
Create Date: 2024-07-22 10:52:17.047650

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df1b99bb595b'
down_revision = '774a1913edb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('package_project',
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('package_id', 'project_id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('packages')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('packages', mysql.VARCHAR(length=400), nullable=True))

    op.drop_table('package_project')
    op.drop_table('package')
    # ### end Alembic commands ###
